program = { declaration }

declaration = stmt 
	| functionDeclaration 
	| structDeclaration
	| enumDeclaration;

stmt = exprStmt
	| varDeclaration
	| ifStmt
	| whileStmt
	| forStmt
	| block;

varDeclaration = ("let" | "const") identifier (":" type | [":" type] "=" expr) ";";
functionDeclaration = ["pub"] "fn" identifier "(" { identifier ":" type "," } [identifier ":" type] ")" [type] block;
enumDeclaration = "enum" identifier "{" {identifier ","} [identifier [","]] "}";
ifStmt = "if" expr block ["else" (ifStmt | block)];
whileStmt = "while" expr block;
// forStmt = "for" "(" varDeclaration ";" expr ";" expr ")" block;
block = "{" {stmt} "}"

assignment = identifier ("=" | "+=" | "-=" | "*=" | "/=" | "%=" | "&=" | "^=" | "|=" | "<<=" | ">>=") expr;
expr = logicalOR;
logicalOR = logicalAND {'||' logicalAND};
logicalAND = comparison {'&&' comparison};
comparison = bitwise [ comparisonOperator bitwise ];
bitwise = bitshift { ('&' | '|' | '^') bitshift };
bitshift = term { ( '<<' | '>>' ) term };
term = factor { ( '+' | '-' ) factor };
factor = unary { ( '*' | '/' | '%' ) unary };
unary = ('!' | '-' | '&') (unary | postfix);
postfix = primary {'.' identifier | '.*' | '[' expr ']' | '(' args ')' };
primary = '(' expr ')' | primative;

comparisonOperator = '>' | '>=' | '<' | '<=' | '==' | '!=';
primative = NUMBER | STRING | CHARACTER | BOOL | NULL | IDENTIFIER | TRUE | FALSE";

