program = { declaration }

declaration = varDeclaration
	| functionDeclaration
	| structDeclaration
	| enumDeclaration
	| stmt;

stmt = varDeclaration
	| ifStmt
	| whileStmt
	| forStmt
	| block;

varDeclaration = ("let" | "const") identifier (":" type | [":" type] "=" expr) ";";
ifStmt = "if" "(" expr ")" block;
whileStmt = "while" "(" expr ")" block;
forStmt = "for" "(" varDeclaration ";" expr ";" expr ")" block;
block = { stmt }

expr = logicalOR;
logicalOR = logicalAND {'||' logicalAND};
logicalAND = comparison {'&&' comparison};
comparison = bitwise [ comparisonOperator bitwise ];
bitwise = bitshift { ('&' | '|' | '^') bitshift };
bitshift = term { ( '<<' | '>>' ) term };
term = factor { ( '+' | '-' ) factor };
factor = unary { ( '*' | '/' | '%' ) unary };
unary = ('!' | '-' | '&') (unary | postfix);
postfix = primary {'.' identifier | '.*' | '[' expr ']' | '(' args ')' };
primary = '(' expr ')' | primative;

comparisonOperator = '>' | '>=' | '<' | '<=' | '==' | '!=';
primative = NUMBER | STRING | CHARACTER | BOOL | NULL | IDENTIFIER | TRUE | FALSE";

